// Projets — repris à l'identique de index.html (const PROJECTS).
// Les URLs des projets suivent la structure /work/<id>.
export const PROJECTS = [
  {
    id: "bcc",
    title: "BCC Esport",
    img: "bcc-esport-logo-identite",
    cat: { fr: "Rebrand & Direction Artistique", en: "Rebrand & Art Direction" },
    year: "2024",
    role: { fr: "Directeur Artistique", en: "Art Director" },
    ph: "Logo, charte ou visuel match-day BCC Esport",
    over: "Refonte complète de l'identité d'une structure esport : logo, charte graphique, système typographique et déclinaisons match-day.",
  },
  {
    id: "coin",
    title: "Team Coin",
    video: "coin",
    cat: { fr: "Identité complète · UI/UX · Site web", en: "Full identity · UI/UX · Website" },
    year: "2023",
    role: { fr: "Design & Développement", en: "Design & Development" },
    live: "https://coin-lan.web.app",
    ph: "Capture du site coin-lan.web.app",
    over: "Conception et développement d'un site événementiel de LAN : plus de 20 pages, design sur-mesure et mise en ligne.",
  },
  {
    id: "deviantart",
    title: "DeviantArt Redesign",
    video: "deviantart-landing-animation",
    cat: { fr: "Rebrand · Refonte landing", en: "Rebrand · Landing redesign" },
    year: "2023",
    role: { fr: "UI/UX Design", en: "UI/UX Design" },
    ph: "Animation de la landing DeviantArt",
    over: "Refonte de la landing DeviantArt : wireframes, design system et interface complète, présentée en animation.",
  },
  {
    id: "preshot",
    title: "Preshot",
    img: "preshot",
    cat: { fr: "App esport · Brand + UI/UX", en: "Esport app · Brand + UI/UX" },
    year: "2025",
    role: { fr: "Brand & Product Design", en: "Brand & Product Design" },
    ph: "Mockups Preshot — 3 écrans (Home · Match · Leaderboard), fond sombre",
    over: "Identité de marque et design system complet pour une app esport de pronostics : logo, palette, typographie, composants et écrans clés.",
  },
  {
    id: "redesign",
    title: "Portfolio",
    anim: true,
    scrollbg: "redesign-bg",
    cat: { fr: "Branding · UI/UX · Dev React", en: "Branding · UI/UX · React dev" },
    year: "2022",
    role: { fr: "UI/UX Design", en: "UI/UX Design" },
    ph: "Mockup Netflix / DeviantArt / Wikipedia",
    over: "Concepts de refonte UI (Netflix, DeviantArt, Wikipedia) avec systèmes de design complets, modes clair/sombre et composants réutilisables.",
  },
  {
    id: "anya",
    title: "Anya",
    img: "anya",
    cat: { fr: "Branding & UI/UX — projet phare", en: "Branding & UI/UX — featured project" },
    year: "2026",
    role: { fr: "Brand & Product Design", en: "Brand & Product Design" },
    ph: "Visuels Anya — identité + écrans clés (à remplacer)",
    over: "Projet mis en avant : identité de marque et expérience produit pour Anya — direction artistique, design system et écrans clés.",
  },
];

// Dégradés de fond des cartes du carrousel (const CARD_BG de index.html).
export const CARD_BG = {
  preshot: ["#0C0E1A", "#1b2140"],
  bcc: ["#15161b", "#262936"],
  coin: ["#1E29FF", "#5b65ff"],
  deviantart: ["#00543d", "#0e7a58"],
  redesign: ["#7a0a12", "#c20f1c"],
  havas: ["#b9701f", "#e29a3f"],
};
