// Services index — repris à l'identique de index.html (SVX_CATS et SVX).
export const SVX_CATS = {
  brand: { fr: "Brand & identité", en: "Brand & identity" },
  uiux: { fr: "UI/UX design", en: "UI/UX design" },
  ds: { fr: "Design system", en: "Design system" },
  tpl: { fr: "Templates & supports", en: "Templates & assets" },
  dev: { fr: "Développement front-end", en: "Front-end development" },
  com: { fr: "Communication", en: "Communication" },
  media: { fr: "Photo & vidéo", en: "Photo & video" },
};

export const SVX = [
  { fr: "Logo", en: "Logo", cat: "brand", d: 2 },
  { fr: "Logo + charte graphique", en: "Logo + brand guidelines", cat: "brand", d: 4 },
  { fr: "Palette de couleurs", en: "Color palette", cat: "brand", d: 0.5 },
  { fr: "Système typographique", en: "Type system", cat: "brand", d: 0.5 },
  { fr: "Charte graphique (sans logo)", en: "Brand guidelines (no logo)", cat: "brand", d: 3 },
  { fr: "Brand book (~10 pages)", en: "Brand book (~10 pages)", cat: "brand", d: 5 },
  { fr: "Brand book complet (20+ pages)", en: "Full brand book (20+ pages)", cat: "brand", d: 8 },
  { fr: "Brand guidelines complet", en: "Full brand guidelines", cat: "brand", d: 10 },
  { fr: "Audit UI/UX + recommandations", en: "UI/UX audit + recommendations", cat: "uiux", d: 0.5 },
  { fr: "Landing page (design seul)", en: "Landing page (design only)", cat: "uiux", d: 2 },
  { fr: "Maquettes site web (5 pages)", en: "Website design (5 pages)", cat: "uiux", d: 5 },
  { fr: "Maquettes site web (10+ pages)", en: "Website design (10+ pages)", cat: "uiux", d: 10 },
  { fr: "Design responsive", en: "Responsive design", cat: "uiux", d: 2 },
  { fr: "App mobile (5 écrans)", en: "Mobile app design (5 screens)", cat: "uiux", d: 5 },
  { fr: "App mobile (10+ écrans)", en: "Mobile app design (10+ screens)", cat: "uiux", d: 10 },
  { fr: "Design system léger", en: "Light design system", cat: "ds", d: 3 },
  { fr: "Design system complet", en: "Full design system", cat: "ds", d: 8 },
  { fr: "Bibliothèque de composants Figma", en: "Figma component library", cat: "ds", d: 4 },
  { fr: "Template document business", en: "Business document template", cat: "tpl", d: 1 },
  { fr: "Set templates réseaux sociaux", en: "Social media template set", cat: "tpl", d: 2 },
  { fr: "Bannières réseaux sociaux", en: "Social media banners", cat: "tpl", d: 0.5 },
  { fr: "Photo de profil / avatar", en: "Profile picture & avatar", cat: "tpl", d: 0.5 },
  { fr: "Affiche / poster", en: "Poster design", cat: "tpl", d: 1 },
  { fr: "Intégration HTML/CSS (landing)", en: "HTML/CSS build (landing)", cat: "dev", d: 4 },
  { fr: "Landing complète (design + intégration)", en: "Full landing (design + build)", cat: "dev", d: 4 },
  { fr: "Intégration site multi-pages", en: "Multi-page website build", cat: "dev", d: 8 },
  { fr: "Community management (mensuel)", en: "Community management (monthly)", cat: "com", d: 10 },
  { fr: "Stratégie réseaux sociaux", en: "Social media strategy", cat: "com", d: 3 },
  { fr: "Pack communication complet", en: "Full communication pack", cat: "com", d: 8 },
  { fr: "Shooting photo (demi-journée)", en: "Photo shoot (half day)", cat: "media", d: 0.5 },
  { fr: "Montage vidéo court", en: "Short video edit", cat: "media", d: 1 },
];
